<?php

namespace App\Console\Commands;

use App\Models\RestaurantMenuPlan;
use App\Models\RestaurantMenuPlanBooking;
use App\Models\RestaurantMenuPlanEntry;
use App\Models\School;
use App\Models\User;
use App\Services\RestaurantBookingService;
use Illuminate\Console\Command;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Support\Carbon;

class RestaurantCreateOrdersCommand extends Command
{
    protected $signature = 'restaurant:create-orders
        {kw : Calendar week number (e.g. 15)}
        {n : Number of orders to create}
        {--year= : Year (defaults to current year)}';

    protected $description = 'Create restaurant orders for the menu plan of a given calendar week.';

    public function __construct(
        private readonly RestaurantBookingService $bookingService
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $kw = (int) $this->argument('kw');
        $count = (int) $this->argument('n');
        $year = (int) ($this->option('year') ?? now()->year);

        if ($kw < 1 || $kw > 53) {
            $this->error("Invalid calendar week: {$kw}");

            return self::FAILURE;
        }

        if ($count < 1) {
            $this->error('The number of orders must be at least 1.');

            return self::FAILURE;
        }

        $monday = Carbon::now()->setISODate($year, $kw, 1)->startOfDay();
        $thursday = $monday->copy()->addDays(3);

        $school = $this->resolveSchool();

        if (! $school) {
            $this->error('School not found.');

            return self::FAILURE;
        }

        $pools = $this->buildOrderPools($school, $monday, $thursday);

        if ($pools['normal'] === [] && $pools['multi'] === []) {
            $this->error("No menu plan found for KW {$kw} or no eligible lunch users with children.");

            return self::FAILURE;
        }

        $this->clearExistingOrders(array_merge($pools['normal'], $pools['multi']));

        $entryCursorByUserAndEatingTime = [];
        $multiOrderSummaries = [];
        $createdCount = 0;

        for ($index = 0; $index < $count; $index++) {
            $useMultiOrder = (($index + 1) % 10 === 0) && $pools['multi'] !== [];
            $pool = $useMultiOrder
                ? $pools['multi']
                : ($pools['normal'] !== [] ? $pools['normal'] : $pools['multi']);
            $contextIndex = $index % count($pool);
            $contextRound = intdiv($index, count($pool));
            $context = $pool[$contextIndex];
            $parent = $context['parent'];
            $recipients = $context['recipients'];
            $eatingTimeId = $context['eating_time_ids'][$contextRound % count($context['eating_time_ids'])] ?? null;
            $entry = $this->nextEntryForEatingTime(
                $context['entries'],
                $eatingTimeId,
                (int) $parent->id,
                $entryCursorByUserAndEatingTime
            );

            if (! $entry) {
                continue;
            }

            $this->bookingService->createBooking($parent, $entry, [
                'restaurant_eating_time_id' => $eatingTimeId,
                'quantity' => count($recipients),
                'recipients' => $recipients,
                'single_recipient_customized' => false,
                'notes' => 'Generated by restaurant:create-orders',
                'booked_at' => now()->copy()->addSeconds($index),
            ]);

            $createdCount++;

            if ($useMultiOrder) {
                $multiOrderSummaries[] = [
                    'number' => $createdCount,
                    'parent' => $this->userDisplayName($parent),
                    'parent_email' => trim((string) $parent->email),
                    'parent_id' => (int) $parent->id,
                    'children_count' => count($recipients),
                ];
            }
        }

        $this->info("Created {$createdCount} orders for KW {$kw}.");

        if ($multiOrderSummaries !== []) {
            $this->line('Parent orders with more than 1 child:');

            foreach ($multiOrderSummaries as $summary) {
                $parentLabel = trim(sprintf(
                    '%s <%s> [#%d]',
                    $summary['parent'],
                    $summary['parent_email'],
                    $summary['parent_id']
                ));

                $this->line(sprintf(
                    '- Order %d: %s (%d children)',
                    $summary['number'],
                    $parentLabel,
                    $summary['children_count']
                ));
            }
        }

        return self::SUCCESS;
    }

    private function resolveSchool(): ?School
    {
        $superAdmin = User::query()->role('super_admin')->first();

        return $superAdmin ? School::query()->find($superAdmin->school_id) : null;
    }

    /**
     * @return array{normal: list<array>, multi: list<array>}
     */
    private function buildOrderPools(School $school, Carbon $monday, Carbon $thursday): array
    {
        $normal = [];
        $multi = [];

        $plan = RestaurantMenuPlan::query()
            ->where('school_id', $school->id)
            ->where('start_date', $monday->toDateString())
            ->where('end_date', $thursday->toDateString())
            ->first();

        if (! $plan) {
            return ['normal' => [], 'multi' => []];
        }

        $entries = RestaurantMenuPlanEntry::query()
            ->with('eatingTimes')
            ->where('restaurant_menu_plan_id', $plan->id)
            ->orderBy('plan_date')
            ->orderBy('id')
            ->get();

        if ($entries->isEmpty()) {
            return ['normal' => [], 'multi' => []];
        }

        $parents = User::query()
            ->role('lunch_user')
            ->where('school_id', $school->id)
            ->orderBy('last_name')
            ->orderBy('first_name')
            ->orderBy('id')
            ->get();

        foreach ($parents as $parent) {
            $singleRecipient = $this->singleRecipientForParent($parent);

            if ($singleRecipient === null) {
                continue;
            }

            $eatingTimeIds = $this->eatingTimeIdsForEntries($entries);

            if ($eatingTimeIds === []) {
                continue;
            }

            $normal[] = [
                'plan' => $plan,
                'parent' => $parent,
                'recipients' => [$singleRecipient],
                'entries' => $entries,
                'eating_time_ids' => $eatingTimeIds,
            ];

            $multiRecipients = $this->multiRecipientsForParent($parent);

            if ($multiRecipients !== null) {
                $multi[] = [
                    'plan' => $plan,
                    'parent' => $parent,
                    'recipients' => $multiRecipients,
                    'entries' => $entries,
                    'eating_time_ids' => $eatingTimeIds,
                ];
            }
        }

        return [
            'normal' => $normal,
            'multi' => $multi,
        ];
    }

    /**
     * @return array{name: string, type: string, import116_id: int|null}|null
     */
    private function singleRecipientForParent(User $user): ?array
    {
        $child = collect($this->bookingService->getChildOptionsForUser($user))
            ->take(2)
            ->first();

        if (! is_array($child)) {
            return null;
        }

        return [
            'name' => $child['name'],
            'type' => 'child',
            'import116_id' => $child['id'],
        ];
    }

    /**
     * @return array<int, array{name: string, type: string, import116_id: int|null}>|null
     */
    private function multiRecipientsForParent(User $user): ?array
    {
        $recipients = collect($this->bookingService->getChildOptionsForUser($user))
            ->take(2)
            ->map(function (array $child): array {
                return [
                    'name' => $child['name'],
                    'type' => 'child',
                    'import116_id' => $child['id'],
                ];
            })
            ->values()
            ->all();

        if (count($recipients) < 2) {
            return null;
        }

        return $recipients;
    }

    /**
     * @param  Collection<int, RestaurantMenuPlanEntry>  $entries
     * @return array<int, int>
     */
    private function eatingTimeIdsForEntries(Collection $entries): array
    {
        return $entries
            ->flatMap(function (RestaurantMenuPlanEntry $entry): array {
                return $entry->eatingTimes->pluck('id')->all();
            })
            ->map(fn (mixed $id): int => (int) $id)
            ->filter(fn (int $id): bool => $id > 0)
            ->unique()
            ->values()
            ->all();
    }

    /**
     * @param  array<string, int>  $entryCursorByUserAndEatingTime
     */
    private function nextEntryForEatingTime(
        Collection $entries,
        ?int $eatingTimeId,
        int $userId,
        array &$entryCursorByUserAndEatingTime,
    ): ?RestaurantMenuPlanEntry {
        if ($entries->isEmpty()) {
            return null;
        }

        $availableEntries = $eatingTimeId !== null
            ? $entries->filter(fn (RestaurantMenuPlanEntry $entry): bool => $entry->eatingTimes->contains(fn ($et): bool => (int) $et->id === $eatingTimeId))->values()
            : $entries;

        if ($availableEntries->isEmpty()) {
            $availableEntries = $entries;
        }

        $cursorKey = $userId.':'.($eatingTimeId ?? 0);
        $cursor = $entryCursorByUserAndEatingTime[$cursorKey] ?? 0;
        $entry = $availableEntries->values()->get($cursor % $availableEntries->count());

        $entryCursorByUserAndEatingTime[$cursorKey] = $cursor + 1;

        return $entry instanceof RestaurantMenuPlanEntry ? $entry : null;
    }

    private function userDisplayName(User $user): string
    {
        $fullName = trim(implode(' ', array_filter([
            trim((string) $user->first_name),
            trim((string) $user->last_name),
        ])));

        return $fullName !== '' ? $fullName : trim((string) $user->email);
    }

    /**
     * @param  array<int, array>  $contexts
     */
    private function clearExistingOrders(array $contexts): void
    {
        $planIds = collect($contexts)
            ->pluck('plan.id')
            ->map(fn (mixed $id): int => (int) $id)
            ->unique()
            ->values()
            ->all();

        if ($planIds === []) {
            return;
        }

        $entryIds = RestaurantMenuPlanEntry::query()
            ->whereIn('restaurant_menu_plan_id', $planIds)
            ->pluck('id')
            ->all();

        if ($entryIds !== []) {
            RestaurantMenuPlanBooking::query()
                ->whereIn('restaurant_menu_plan_entry_id', $entryIds)
                ->delete();
        }
    }
}
