<?php

return [
    'version' => '2026-03-16',
    'domain' => 'ahs-aba',
    'scope' => [
        'school_type' => 'AHS',
        'excluded_school_types' => ['BMHS', 'BHS'],
        'knowledge_source' => 'ai/knowledge/aba/sources/aba-knowledge-seed-report.md',
        'note' => 'Schulspezifische Punkte sind markiert und dürfen nicht als harte Automatikbewertung behandelt werden.',
    ],
    'assessment_classes' => [
        'verbindlich_pruefbar' => [
            'label' => 'verbindlich prüfbar',
            'description' => 'Regeln mit klarer, deterministischer Prüfbarkeit.',
        ],
        'plausibilisierbar' => [
            'label' => 'plausibilisierbar',
            'description' => 'Automatisch nur als Plausibilitätsprüfung auswertbar, mit manueller Nachprüfung.',
        ],
        'hinweis_vorsichtig' => [
            'label' => 'nur als Hinweis / vorsichtig bewertbar',
            'description' => 'Automatisch nur als weicher Hinweis, nicht als harte Abwertung.',
        ],
        'schulspezifisch_offen' => [
            'label' => 'schulspezifisch / offen',
            'description' => 'Abhängig von Standortvorgaben oder noch nicht abschließend geklärt.',
        ],
    ],
    'detection' => [
        'section_type_patterns' => [
            'title_page' => '/^\s*(titelblatt|titelseite|deckblatt)\b/iu',
            'abstract' => '/^\s*(abstract|zusammenfassung|kurzfassung|summary|executive summary|management summary|kurz[üu]berblick)(?:\s*(?:\(|\[)?\s*(deutsch|german|englisch|english)\s*(?:\)|\])?)?\s*(?:$|[:\-–]\s*[^.!?]{0,120}$|(?:(?:\.{2,}|…+)\s*)?\d+(?:\s*[-–]\s*\d+)?\s*$)/iu',
            'foreword' => '/^\s*(vorwort|vorbemerkung|preface|foreword|prefazione)\b/iu',
            'table_of_contents' => '/^\s*(inhaltsverzeichnis|table of contents)\b/iu',
            'bibliography' => '/^\s*(?:(?:literaturverzeichnis|literaturangaben|quellenverzeichnis|quellenangaben|verwendete\s+quellen|literatur(?:\s*[-–]\s*|\s+und\s+)quellenverzeichnis|internetquellenverzeichnis|internetverzeichnis|internetquellenangaben|internetquellenliste|internetquellen|internet|webquellenverzeichnis|web(?:\s*-\s*|\s*)quellen|webquellen|onlinequellenverzeichnis|online(?:\s*-\s*|\s*)quellen|onlinequellen|webseiten|weblinks|references|bibliography|bibliograph(?:ie|y)|bibliografie)\b|(?:quellen?|quelle)\s*(?:$|[:\-–]\s*$))/iu',
            'figure_index' => '/^\s*(?:\d+(?:\.\d+){0,5}\s+)?(?:abbildungsverzeichnis|tabellenverzeichnis|abbildung(?:s)?\s*[-–]?\s*(?:und|&)\s*tabellenverzeichnis|list of figures(?: and tables)?|list of tables)\b/iu',
            'consent_declaration' => '/^\s*(?:einverst[aä]ndniserkl[aä]rung|einverstaendniserklaerung|eigenst[aä]ndigkeitserkl[aä]rung|selbstst[aä]ndigkeitserkl[aä]rung|selbststaendigkeitserklaerung|eidesstattliche\s+erkl[aä]rung|eidesstaatliche\s+erkl[aä]rung|eidstaatliche\s+erkl[aä]rung|ehrenw[oö]rtliche\s+erkl[aä]rung|erkl[aä]rung)\s*(?:$|[:\-–]\s*[^.!?]{0,120}$)/iu',
        ],
        'chapter_heading_pattern' => '/^\s*(?:einleitung|introduction|hauptteil|methodik|methoden|ergebnisse|diskussion|fazit|schluss(?:folgerung)?|conclusion|conclusio|res[üu]mee|ausblick|anhang|appendix|beilage[n]?)(?:\s*\/\s*(?:fazit|schluss(?:folgerung)?|conclusion|conclusio|res[üu]mee|ausblick))?\s*(?:$|[:\-–]\s*[^.!?]{0,120}$)/iu',
        'section_keyword_pattern' => '/\b(abstract|zusammenfassung|kurzfassung|vorwort|vorbemerkung|inhaltsverzeichnis|literaturverzeichnis|quellenverzeichnis|bibliography|references|abbildungsverzeichnis|tabellenverzeichnis|eigenst[aä]ndigkeitserkl[aä]rung|selbstst[aä]ndigkeitserkl[aä]rung|einverst[aä]ndniserkl[aä]rung|eidesstattliche\s+erkl[aä]rung|einleitung|hauptteil|fazit|conclusio|anhang|begleitprotokoll)\b/iu',
    ],
    'structure_rules' => [
        'sections' => [
            'title_page' => [
                'label' => 'Titelblatt',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'title_page',
                'school_specific' => false,
                'accepted_headings' => ['Titelblatt', 'Titelseite', 'Deckblatt'],
            ],
            'table_of_contents' => [
                'label' => 'Inhaltsverzeichnis',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'table_of_contents',
                'school_specific' => false,
                'accepted_headings' => ['Inhaltsverzeichnis', 'Table of Contents'],
            ],
            'abstract_de' => [
                'label' => 'Abstract Deutsch',
                'requirement' => 'pflicht',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'abstract',
                'school_specific' => false,
                'accepted_headings' => ['Abstract (Deutsch)', 'Zusammenfassung', 'Kurzfassung'],
                'notes' => ['Länge 1.000-1.500 Zeichen laut Seed ist plausibilisierbar, nicht final hart automatisiert.'],
            ],
            'abstract_en' => [
                'label' => 'Abstract Englisch',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'abstract',
                'school_specific' => false,
                'accepted_headings' => ['Abstract (English)', 'Abstract', 'Summary'],
                'notes' => ['Sprachzuordnung ist heuristisch und nur plausibilisierbar.', 'Englisches Abstract ist optional. Fehlend = kein kritischer Fehler.'],
            ],
            'introduction' => [
                'label' => 'Einleitung',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => false,
                'accepted_headings' => ['Einleitung', 'Introduction'],
            ],
            'main_body' => [
                'label' => 'Hauptteil',
                'requirement' => 'pflicht',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => true,
                'accepted_headings' => ['Hauptteil', 'Methodik', 'Ergebnisse', 'Diskussion'],
                'notes' => ['Feingliederung ist schulspezifisch und themenabhängig.'],
            ],
            'conclusion' => [
                'label' => 'Schluss / Fazit / Conclusio',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => false,
                'accepted_headings' => ['Schluss', 'Fazit', 'Conclusio', 'Conclusion', 'Resümee', 'Ausblick'],
            ],
            'bibliography' => [
                'label' => 'Literaturverzeichnis',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'bibliography',
                'school_specific' => false,
                'accepted_headings' => ['Literaturverzeichnis', 'Quellenverzeichnis', 'Bibliography', 'References'],
            ],
            'consent_declaration' => [
                'label' => 'Eigenständigkeitserklärung',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'consent_declaration',
                'school_specific' => false,
                'accepted_headings' => ['Eigenständigkeitserklärung', 'Selbstständigkeitserklärung', 'Eidesstattliche Erklärung'],
            ],
            'appendix' => [
                'label' => 'Anhang',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => true,
                'accepted_headings' => ['Anhang', 'Appendix', 'Beilagen'],
            ],
            'figure_index' => [
                'label' => 'Abbildungs- / Tabellenverzeichnis',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'figure_index',
                'school_specific' => true,
                'accepted_headings' => ['Abbildungsverzeichnis', 'Tabellenverzeichnis', 'List of Figures', 'List of Tables'],
            ],
            'accompanying_log' => [
                'label' => 'Begleitprotokoll',
                'requirement' => 'schulspezifisch',
                'assessment_class' => 'schulspezifisch_offen',
                'maps_to_section_type' => null,
                'school_specific' => true,
                'accepted_headings' => ['Begleitprotokoll', 'Prozessdokumentation'],
                'notes' => ['Kann als separates Dokument geführt werden und muss daher nicht im Hauptdokument extrahierbar sein.'],
            ],
        ],
    ],
    'document_zone_rules' => [
        'zones' => [
            'titlepage' => [
                'label' => 'Titelblatt',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'title_page',
                'school_specific' => false,
                'heading_variants' => ['Titelblatt', 'Deckblatt'],
                'keyword_signals' => ['Schule', 'Schuljahr', 'Betreuungsperson', 'Name'],
                'position_hints' => ['Dokumentanfang', 'vor Abstract/TOC'],
                'pattern_hints' => ['kurze Metadatenzeilen', 'prominenter Dokumenttitel'],
                'content_hints' => ['Dokumentmetadaten statt Fließtext'],
            ],
            'abstract_de' => [
                'label' => 'Abstract Deutsch',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'abstract',
                'school_specific' => false,
                'heading_variants' => ['Zusammenfassung', 'Kurzfassung', 'Abstract (Deutsch)'],
                'keyword_signals' => ['Zusammenfassung', 'Deutsch'],
                'position_hints' => ['vor Einleitung', 'nach Titelblatt'],
                'pattern_hints' => ['kompakter Überblick', 'keine Kapitelnummer'],
                'content_hints' => ['Fragestellung, Vorgehen, Ergebnis kurz zusammengefasst'],
            ],
            'abstract_en' => [
                'label' => 'Abstract Englisch',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'abstract',
                'school_specific' => false,
                'heading_variants' => ['Abstract (English)', 'Summary', 'Executive Summary'],
                'keyword_signals' => ['Abstract', 'English', 'Summary'],
                'position_hints' => ['nahe beim deutschen Abstract'],
                'pattern_hints' => ['sprachliche Parallelfassung zum deutschen Abstract'],
                'content_hints' => ['optional; fehlend darf nicht kritisch gewertet werden'],
            ],
            'toc' => [
                'label' => 'Inhaltsverzeichnis',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'table_of_contents',
                'school_specific' => false,
                'heading_variants' => ['Inhaltsverzeichnis', 'Table of Contents'],
                'keyword_signals' => ['Inhaltsverzeichnis', 'Seitenzahlmuster'],
                'position_hints' => ['vor Einleitung', 'nach Frontmatter'],
                'pattern_hints' => ['viele kurze Einträge mit Seitenzahlen'],
                'content_hints' => ['verweist auf spätere Kapitel, kein Fließtextabschnitt'],
            ],
            'introduction' => [
                'label' => 'Einleitung',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => false,
                'heading_variants' => ['Einleitung', 'Introduction'],
                'keyword_signals' => ['Fragestellung', 'Zielsetzung', 'Vorgehen'],
                'position_hints' => ['nach TOC/Abstract'],
                'pattern_hints' => ['erstes Hauptkapitel im Fließtext'],
                'content_hints' => ['Kontext und Ziel der Arbeit'],
            ],
            'main_part' => [
                'label' => 'Hauptteil',
                'requirement' => 'required',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => true,
                'heading_variants' => ['Hauptteil', 'Methodik', 'Ergebnisse', 'Diskussion'],
                'keyword_signals' => ['Kapitelnummern', 'Unterkapitel'],
                'position_hints' => ['nach Einleitung', 'vor Schluss'],
                'pattern_hints' => ['längster Fließtextbereich'],
                'content_hints' => ['fachliche Ausarbeitung und Argumentation'],
            ],
            'conclusion' => [
                'label' => 'Schluss / Fazit / Conclusio',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => false,
                'heading_variants' => ['Schluss', 'Fazit', 'Conclusio', 'Conclusion', 'Resümee', 'Ausblick'],
                'keyword_signals' => ['Zusammenfassung', 'Reflexion', 'Ausblick'],
                'position_hints' => ['nach Hauptteil', 'vor Bibliographie'],
                'pattern_hints' => ['abschließendes Kapitel ohne Unterkapitelinflation'],
                'content_hints' => ['Erkenntnisse, Grenzen, Ausblick'],
            ],
            'bibliography' => [
                'label' => 'Literatur-/Quellenverzeichnis',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'bibliography',
                'school_specific' => false,
                'heading_variants' => ['Literaturverzeichnis', 'Quellenverzeichnis', 'Internetquellenverzeichnis', 'Bibliography', 'References'],
                'keyword_signals' => ['Autor', 'Titel', 'Jahr', 'URL', 'Zugriff'],
                'position_hints' => ['nach Schluss'],
                'pattern_hints' => ['listenhafte Einträge mit Quellenmetadaten'],
                'content_hints' => ['keine inhaltlichen Kapitelabsätze'],
            ],
            'declaration' => [
                'label' => 'Eigenständigkeitserklärung',
                'requirement' => 'required',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'consent_declaration',
                'school_specific' => false,
                'heading_variants' => ['Eigenständigkeitserklärung', 'Selbstständigkeitserklärung', 'Eidesstattliche Erklärung'],
                'keyword_signals' => ['hiermit erkläre', 'eidesstattlich', 'Unterschrift', 'Datum'],
                'position_hints' => ['Dokumentende'],
                'pattern_hints' => ['kurzer formaler Erklärungstext'],
                'content_hints' => ['Abschlussbestandteil, kein Fachkapitel'],
            ],
            'appendix' => [
                'label' => 'Anhang',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => true,
                'heading_variants' => ['Anhang', 'Appendix', 'Beilagen'],
                'keyword_signals' => ['Anhang', 'Beilage'],
                'position_hints' => ['nach Hauptteil/Schluss'],
                'pattern_hints' => ['zusätzliche Materialien'],
                'content_hints' => ['unterstützende Dokumente, Tabellen, Rohdaten'],
            ],
            'figure_table_index' => [
                'label' => 'Abbildungs-/Tabellenverzeichnis',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'figure_index',
                'school_specific' => true,
                'heading_variants' => ['Abbildungsverzeichnis', 'Tabellenverzeichnis', 'List of Figures', 'List of Tables'],
                'keyword_signals' => ['Abbildung', 'Tabelle', 'Seitenzahl'],
                'position_hints' => ['vor oder nach Bibliographie möglich'],
                'pattern_hints' => ['listenhafte Verzeichniseinträge'],
                'content_hints' => ['Verzeichnisbereich, kein Fließtextkapitel'],
            ],
        ],
        'sequence_rules' => [
            [
                'rule_key' => 'titlepage_before_toc',
                'label' => 'Titelblatt vor Inhaltsverzeichnis',
                'from_zone' => 'titlepage',
                'to_zone' => 'toc',
                'assessment_class' => 'plausibilisierbar',
                'strictness' => 'soft',
                'note' => 'Bei abweichender Reihenfolge nur Hinweis, keine harte Abwertung.',
            ],
            [
                'rule_key' => 'toc_before_introduction',
                'label' => 'Inhaltsverzeichnis vor Einleitung',
                'from_zone' => 'toc',
                'to_zone' => 'introduction',
                'assessment_class' => 'plausibilisierbar',
                'strictness' => 'soft',
                'note' => 'Hilft TOC-Block von Fließtext-Kapiteln zu trennen.',
            ],
            [
                'rule_key' => 'conclusion_before_bibliography',
                'label' => 'Schluss vor Bibliographie',
                'from_zone' => 'conclusion',
                'to_zone' => 'bibliography',
                'assessment_class' => 'plausibilisierbar',
                'strictness' => 'soft',
                'note' => 'Abweichungen können schulspezifisch sein.',
            ],
            [
                'rule_key' => 'declaration_at_end',
                'label' => 'Erklärung im Endbereich',
                'from_zone' => 'declaration',
                'to_zone' => null,
                'assessment_class' => 'verbindlich_pruefbar',
                'strictness' => 'medium',
                'note' => 'Erklärung soll am Ende liegen; danach nur Endmatter/Unterschrift.',
            ],
            [
                'rule_key' => 'appendix_after_main',
                'label' => 'Anhang nach Hauptteil',
                'from_zone' => 'main_part',
                'to_zone' => 'appendix',
                'assessment_class' => 'schulspezifisch_offen',
                'strictness' => 'soft',
                'note' => 'Anhang ist optional und schulspezifisch.',
            ],
        ],
    ],
    'formal_rules' => [
        [
            'rule_key' => 'contains_abstract_sections',
            'label' => 'Abstract Deutsch vorhanden, Abstract Englisch optional',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'check_hint' => 'Deutsches Abstract verbindlich prüfen; englisches Abstract optional erkennen und nur hinweisartig bewerten.',
        ],
        [
            'rule_key' => 'contains_bibliography_section',
            'label' => 'Literaturverzeichnis vorhanden',
            'assessment_class' => 'verbindlich_pruefbar',
            'binding_in_seed' => true,
            'check_hint' => 'Mindestens ein Bibliographie-Abschnitt erkannt.',
        ],
        [
            'rule_key' => 'contains_consent_declaration',
            'label' => 'Eigenständigkeitserklärung vorhanden',
            'assessment_class' => 'verbindlich_pruefbar',
            'binding_in_seed' => true,
            'check_hint' => 'Mindestens ein Abschnitt für Erklärung erkannt.',
        ],
        [
            'rule_key' => 'accompanying_log_submission',
            'label' => 'Begleitprotokoll mit Abgabe',
            'assessment_class' => 'schulspezifisch_offen',
            'binding_in_seed' => true,
            'check_hint' => 'Dokument kann außerhalb des Hauptdokuments liegen und muss separat geprüft werden.',
        ],
    ],
    'language_rules' => [
        [
            'rule_key' => 'spelling_grammar_assistive_check',
            'label' => 'Rechtschreibung und Grammatik als Assistenzprüfung',
            'assessment_class' => 'hinweis_vorsichtig',
            'binding_in_seed' => false,
            'automation_scope' => 'Automatische Treffer sind Hinweise und nicht alleinige Bewertungsgrundlage.',
        ],
        [
            'rule_key' => 'readability_and_style',
            'label' => 'Stil und Verständlichkeit',
            'assessment_class' => 'hinweis_vorsichtig',
            'binding_in_seed' => false,
            'automation_scope' => 'Nur Hinweise auf unklare Passagen, keine harte Punktvergabe.',
        ],
        [
            'rule_key' => 'language_quality_weight',
            'label' => 'Sprachqualität als Bewertungskriterium',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'automation_scope' => 'Automatik liefert Indikatoren, Endbewertung bleibt menschlich.',
        ],
    ],
    'citation_rules' => [
        [
            'rule_key' => 'sources_must_be_cited',
            'label' => 'Externe Quellen müssen zitiert sein',
            'assessment_class' => 'verbindlich_pruefbar',
            'binding_in_seed' => true,
            'automation_scope' => 'Existenz von Quellenhinweisen und Literaturverzeichnis prüfbar.',
        ],
        [
            'rule_key' => 'citation_style_consistency',
            'label' => 'Zitiersystem konsistent',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'automation_scope' => 'Konsistenzmuster prüfbar, endgültige Stilkonformität manuell.',
        ],
        [
            'rule_key' => 'web_sources_with_access_date',
            'label' => 'Webquellen mit Zugriffsdatum',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'automation_scope' => 'URL + Datumsindikatoren automatisch suchbar, Vollständigkeit manuell bestätigen.',
        ],
        [
            'rule_key' => 'ai_source_disclosure',
            'label' => 'KI-Quellen transparent dokumentieren',
            'assessment_class' => 'hinweis_vorsichtig',
            'binding_in_seed' => true,
            'automation_scope' => 'Nur Hinweisprüfung auf Offenlegung; keine automatische Täuschungsbewertung.',
        ],
        [
            'rule_key' => 'minimum_source_count',
            'label' => 'Mindestanzahl Quellen',
            'assessment_class' => 'schulspezifisch_offen',
            'binding_in_seed' => true,
            'automation_scope' => 'Anzahl kann je Schule variieren (Seed: oft 8-15).',
        ],
    ],
    'uncertainty_and_school_dependency_rules' => [
        [
            'rule_key' => 'submission_dates_are_school_specific',
            'label' => 'Abgabetermine sind schulspezifisch',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Nur markieren, nicht hart bewerten.',
        ],
        [
            'rule_key' => 'page_count_is_school_specific',
            'label' => 'Seitenumfang ist schulspezifisch',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Keine harte Automatik auf Seitenzahl.',
        ],
        [
            'rule_key' => 'format_b_availability_uncertain',
            'label' => 'Format B Verfügbarkeit offen',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Nicht als global verpflichtende Regel behandeln.',
        ],
        [
            'rule_key' => 'evaluation_raster_after_2026_27_not_final',
            'label' => 'Bewertungsraster ab 2026/27 teilweise offen',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Nur vorsichtige Einordnung, kein hartes Scoring.',
        ],
    ],
    'governance_and_safety_rules' => [
        [
            'rule_key' => 'no_hard_auto_grading_for_uncertain_rules',
            'label' => 'Keine harte Auto-Bewertung bei unsicheren Regeln',
            'assessment_class' => 'verbindlich_pruefbar',
            'enforcement' => 'Ergebnisse aus hinweis_vorsichtig und schulspezifisch_offen niemals als automatische Endabwertung verwenden.',
        ],
        [
            'rule_key' => 'transparent_rule_trace',
            'label' => 'Bewertung mit Regelbezug begründen',
            'assessment_class' => 'verbindlich_pruefbar',
            'enforcement' => 'Jeder automatische Hinweis sollte rule_key und assessment_class tragen.',
        ],
        [
            'rule_key' => 'extraction_failure_transparency',
            'label' => 'Extraktionsstatus explizit',
            'assessment_class' => 'verbindlich_pruefbar',
            'enforcement' => 'Zwischen erfolgreich, teilweise und nicht extrahierbar unterscheiden.',
        ],
    ],
];
