<?php

return [
    'version' => '2026-03-16',
    'domain' => 'ahs-aba',
    'scope' => [
        'school_type' => 'AHS',
        'excluded_school_types' => ['BMHS', 'BHS'],
        'knowledge_source' => 'ai/knowledge/aba/sources/aba-knowledge-seed-report.md',
        'note' => 'Schulspezifische Punkte sind markiert und dürfen nicht als harte Automatikbewertung behandelt werden.',
    ],
    'assessment_classes' => [
        'verbindlich_pruefbar' => [
            'label' => 'verbindlich prüfbar',
            'description' => 'Regeln mit klarer, deterministischer Prüfbarkeit.',
        ],
        'plausibilisierbar' => [
            'label' => 'plausibilisierbar',
            'description' => 'Automatisch nur als Plausibilitätsprüfung auswertbar, mit manueller Nachprüfung.',
        ],
        'hinweis_vorsichtig' => [
            'label' => 'nur als Hinweis / vorsichtig bewertbar',
            'description' => 'Automatisch nur als weicher Hinweis, nicht als harte Abwertung.',
        ],
        'schulspezifisch_offen' => [
            'label' => 'schulspezifisch / offen',
            'description' => 'Abhängig von Standortvorgaben oder noch nicht abschließend geklärt.',
        ],
    ],
    'detection' => [
        'section_type_patterns' => [
            'title_page' => '/^\s*(titelblatt|deckblatt)\b/iu',
            'abstract' => '/^\s*(abstract|zusammenfassung|kurzfassung|summary|executive summary|management summary|kurz[üu]berblick)(?:\s*(?:\(|\[)?\s*(deutsch|german|englisch|english)\s*(?:\)|\])?)?\s*(?:$|[:\-–]\s*[^.!?]{0,120}$|(?:(?:\.{2,}|…+)\s*)?\d+(?:\s*[-–]\s*\d+)?\s*$)/iu',
            'foreword' => '/^\s*(vorwort|vorbemerkung|preface|foreword|prefazione)\b/iu',
            'table_of_contents' => '/^\s*(inhaltsverzeichnis|table of contents)\b/iu',
            'bibliography' => '/^\s*(?:(?:literaturverzeichnis|literaturangaben|quellenverzeichnis|quellenangaben|verwendete\s+quellen|literatur(?:\s*[-–]\s*|\s+und\s+)quellenverzeichnis|internetquellenverzeichnis|internetverzeichnis|internetquellenangaben|internetquellenliste|internetquellen|internet|webquellenverzeichnis|web(?:\s*-\s*|\s*)quellen|webquellen|onlinequellenverzeichnis|online(?:\s*-\s*|\s*)quellen|onlinequellen|webseiten|weblinks|references|bibliography|bibliograph(?:ie|y)|bibliografie)\b|(?:quellen?|quelle)\s*(?:$|[:\-–]\s*$))/iu',
            'figure_index' => '/^\s*(?:\d+(?:\.\d+){0,5}\s+)?(?:abbildungsverzeichnis|tabellenverzeichnis|abbildung(?:s)?\s*[-–]?\s*(?:und|&)\s*tabellenverzeichnis|list of figures(?: and tables)?|list of tables)\b/iu',
            'consent_declaration' => '/^\s*(?:einverst[aä]ndniserkl[aä]rung|einverstaendniserklaerung|eigenst[aä]ndigkeitserkl[aä]rung|selbstst[aä]ndigkeitserkl[aä]rung|selbststaendigkeitserklaerung|eidesstattliche\s+erkl[aä]rung|eidesstaatliche\s+erkl[aä]rung|eidstaatliche\s+erkl[aä]rung|ehrenw[oö]rtliche\s+erkl[aä]rung|erkl[aä]rung)\s*(?:$|[:\-–]\s*[^.!?]{0,120}$)/iu',
        ],
        'chapter_heading_pattern' => '/^\s*(?:einleitung|introduction|hauptteil|methodik|methoden|ergebnisse|diskussion|fazit|schluss(?:folgerung)?|conclusion|conclusio|res[üu]mee|ausblick|anhang|appendix|beilage[n]?)(?:\s*\/\s*(?:fazit|schluss(?:folgerung)?|conclusion|conclusio|res[üu]mee|ausblick))?\s*(?:$|[:\-–]\s*[^.!?]{0,120}$)/iu',
        'section_keyword_pattern' => '/\b(abstract|zusammenfassung|kurzfassung|vorwort|vorbemerkung|inhaltsverzeichnis|literaturverzeichnis|quellenverzeichnis|bibliography|references|abbildungsverzeichnis|tabellenverzeichnis|eigenst[aä]ndigkeitserkl[aä]rung|selbstst[aä]ndigkeitserkl[aä]rung|einverst[aä]ndniserkl[aä]rung|eidesstattliche\s+erkl[aä]rung|einleitung|hauptteil|fazit|conclusio|anhang|begleitprotokoll)\b/iu',
    ],
    'structure_rules' => [
        'sections' => [
            'title_page' => [
                'label' => 'Titelblatt',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'title_page',
                'school_specific' => false,
                'accepted_headings' => ['Titelblatt', 'Deckblatt'],
            ],
            'table_of_contents' => [
                'label' => 'Inhaltsverzeichnis',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'table_of_contents',
                'school_specific' => false,
                'accepted_headings' => ['Inhaltsverzeichnis', 'Table of Contents'],
            ],
            'abstract_de' => [
                'label' => 'Abstract Deutsch',
                'requirement' => 'pflicht',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'abstract',
                'school_specific' => false,
                'accepted_headings' => ['Abstract (Deutsch)', 'Zusammenfassung', 'Kurzfassung'],
                'notes' => ['Länge 1.000-1.500 Zeichen laut Seed ist plausibilisierbar, nicht final hart automatisiert.'],
            ],
            'abstract_en' => [
                'label' => 'Abstract Englisch',
                'requirement' => 'pflicht',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'abstract',
                'school_specific' => false,
                'accepted_headings' => ['Abstract (English)', 'Abstract', 'Summary'],
                'notes' => ['Sprachzuordnung ist heuristisch und nur plausibilisierbar.'],
            ],
            'introduction' => [
                'label' => 'Einleitung',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => false,
                'accepted_headings' => ['Einleitung', 'Introduction'],
            ],
            'main_body' => [
                'label' => 'Hauptteil',
                'requirement' => 'pflicht',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => true,
                'accepted_headings' => ['Hauptteil', 'Methodik', 'Ergebnisse', 'Diskussion'],
                'notes' => ['Feingliederung ist schulspezifisch und themenabhängig.'],
            ],
            'conclusion' => [
                'label' => 'Schluss / Fazit / Conclusio',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => false,
                'accepted_headings' => ['Schluss', 'Fazit', 'Conclusio', 'Conclusion', 'Resümee', 'Ausblick'],
            ],
            'bibliography' => [
                'label' => 'Literaturverzeichnis',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'bibliography',
                'school_specific' => false,
                'accepted_headings' => ['Literaturverzeichnis', 'Quellenverzeichnis', 'Bibliography', 'References'],
            ],
            'consent_declaration' => [
                'label' => 'Eigenständigkeitserklärung',
                'requirement' => 'pflicht',
                'assessment_class' => 'verbindlich_pruefbar',
                'maps_to_section_type' => 'consent_declaration',
                'school_specific' => false,
                'accepted_headings' => ['Eigenständigkeitserklärung', 'Selbstständigkeitserklärung', 'Eidesstattliche Erklärung'],
            ],
            'appendix' => [
                'label' => 'Anhang',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'chapter',
                'school_specific' => true,
                'accepted_headings' => ['Anhang', 'Appendix', 'Beilagen'],
            ],
            'figure_index' => [
                'label' => 'Abbildungs- / Tabellenverzeichnis',
                'requirement' => 'optional',
                'assessment_class' => 'plausibilisierbar',
                'maps_to_section_type' => 'figure_index',
                'school_specific' => true,
                'accepted_headings' => ['Abbildungsverzeichnis', 'Tabellenverzeichnis', 'List of Figures', 'List of Tables'],
            ],
            'accompanying_log' => [
                'label' => 'Begleitprotokoll',
                'requirement' => 'schulspezifisch',
                'assessment_class' => 'schulspezifisch_offen',
                'maps_to_section_type' => null,
                'school_specific' => true,
                'accepted_headings' => ['Begleitprotokoll', 'Prozessdokumentation'],
                'notes' => ['Kann als separates Dokument geführt werden und muss daher nicht im Hauptdokument extrahierbar sein.'],
            ],
        ],
    ],
    'formal_rules' => [
        [
            'rule_key' => 'contains_abstract_sections',
            'label' => 'Deutsch- und Englisch-Abstract vorhanden',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'check_hint' => 'Mindestens ein deutscher und ein englischer Abstract im Hauptdokument oder separater Nachweis.',
        ],
        [
            'rule_key' => 'contains_bibliography_section',
            'label' => 'Literaturverzeichnis vorhanden',
            'assessment_class' => 'verbindlich_pruefbar',
            'binding_in_seed' => true,
            'check_hint' => 'Mindestens ein Bibliographie-Abschnitt erkannt.',
        ],
        [
            'rule_key' => 'contains_consent_declaration',
            'label' => 'Eigenständigkeitserklärung vorhanden',
            'assessment_class' => 'verbindlich_pruefbar',
            'binding_in_seed' => true,
            'check_hint' => 'Mindestens ein Abschnitt für Erklärung erkannt.',
        ],
        [
            'rule_key' => 'accompanying_log_submission',
            'label' => 'Begleitprotokoll mit Abgabe',
            'assessment_class' => 'schulspezifisch_offen',
            'binding_in_seed' => true,
            'check_hint' => 'Dokument kann außerhalb des Hauptdokuments liegen und muss separat geprüft werden.',
        ],
    ],
    'language_rules' => [
        [
            'rule_key' => 'spelling_grammar_assistive_check',
            'label' => 'Rechtschreibung und Grammatik als Assistenzprüfung',
            'assessment_class' => 'hinweis_vorsichtig',
            'binding_in_seed' => false,
            'automation_scope' => 'Automatische Treffer sind Hinweise und nicht alleinige Bewertungsgrundlage.',
        ],
        [
            'rule_key' => 'readability_and_style',
            'label' => 'Stil und Verständlichkeit',
            'assessment_class' => 'hinweis_vorsichtig',
            'binding_in_seed' => false,
            'automation_scope' => 'Nur Hinweise auf unklare Passagen, keine harte Punktvergabe.',
        ],
        [
            'rule_key' => 'language_quality_weight',
            'label' => 'Sprachqualität als Bewertungskriterium',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'automation_scope' => 'Automatik liefert Indikatoren, Endbewertung bleibt menschlich.',
        ],
    ],
    'citation_rules' => [
        [
            'rule_key' => 'sources_must_be_cited',
            'label' => 'Externe Quellen müssen zitiert sein',
            'assessment_class' => 'verbindlich_pruefbar',
            'binding_in_seed' => true,
            'automation_scope' => 'Existenz von Quellenhinweisen und Literaturverzeichnis prüfbar.',
        ],
        [
            'rule_key' => 'citation_style_consistency',
            'label' => 'Zitiersystem konsistent',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'automation_scope' => 'Konsistenzmuster prüfbar, endgültige Stilkonformität manuell.',
        ],
        [
            'rule_key' => 'web_sources_with_access_date',
            'label' => 'Webquellen mit Zugriffsdatum',
            'assessment_class' => 'plausibilisierbar',
            'binding_in_seed' => true,
            'automation_scope' => 'URL + Datumsindikatoren automatisch suchbar, Vollständigkeit manuell bestätigen.',
        ],
        [
            'rule_key' => 'ai_source_disclosure',
            'label' => 'KI-Quellen transparent dokumentieren',
            'assessment_class' => 'hinweis_vorsichtig',
            'binding_in_seed' => true,
            'automation_scope' => 'Nur Hinweisprüfung auf Offenlegung; keine automatische Täuschungsbewertung.',
        ],
        [
            'rule_key' => 'minimum_source_count',
            'label' => 'Mindestanzahl Quellen',
            'assessment_class' => 'schulspezifisch_offen',
            'binding_in_seed' => true,
            'automation_scope' => 'Anzahl kann je Schule variieren (Seed: oft 8-15).',
        ],
    ],
    'uncertainty_and_school_dependency_rules' => [
        [
            'rule_key' => 'submission_dates_are_school_specific',
            'label' => 'Abgabetermine sind schulspezifisch',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Nur markieren, nicht hart bewerten.',
        ],
        [
            'rule_key' => 'page_count_is_school_specific',
            'label' => 'Seitenumfang ist schulspezifisch',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Keine harte Automatik auf Seitenzahl.',
        ],
        [
            'rule_key' => 'format_b_availability_uncertain',
            'label' => 'Format B Verfügbarkeit offen',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Nicht als global verpflichtende Regel behandeln.',
        ],
        [
            'rule_key' => 'evaluation_raster_after_2026_27_not_final',
            'label' => 'Bewertungsraster ab 2026/27 teilweise offen',
            'assessment_class' => 'schulspezifisch_offen',
            'automation_scope' => 'Nur vorsichtige Einordnung, kein hartes Scoring.',
        ],
    ],
    'governance_and_safety_rules' => [
        [
            'rule_key' => 'no_hard_auto_grading_for_uncertain_rules',
            'label' => 'Keine harte Auto-Bewertung bei unsicheren Regeln',
            'assessment_class' => 'verbindlich_pruefbar',
            'enforcement' => 'Ergebnisse aus hinweis_vorsichtig und schulspezifisch_offen niemals als automatische Endabwertung verwenden.',
        ],
        [
            'rule_key' => 'transparent_rule_trace',
            'label' => 'Bewertung mit Regelbezug begründen',
            'assessment_class' => 'verbindlich_pruefbar',
            'enforcement' => 'Jeder automatische Hinweis sollte rule_key und assessment_class tragen.',
        ],
        [
            'rule_key' => 'extraction_failure_transparency',
            'label' => 'Extraktionsstatus explizit',
            'assessment_class' => 'verbindlich_pruefbar',
            'enforcement' => 'Zwischen erfolgreich, teilweise und nicht extrahierbar unterscheiden.',
        ],
    ],
];
