<?php

return [
    'version' => '3.32.0',
    'copyright' => '(c) 2025 – 2026 ITStudio.at by Günther Kron',
    'logo' => 'schooltool_white.png',
    'pagination' => 30,
    'token_expire_time' => 60,
    'noreply_email' => 'noreply@schooltool.at',
    'sa_pw' => env('SA_PW'),
    'sa_last_name' => env('SA_LAST_NAME', ''),
    'sa_first_name' => env('SA_FIRST_NAME', ''),
    'sa_email' => env('SA_EMAIL', ''),
    'email_aliases' => [
        'a@a.at' => 'kron@naturwelt.at',
    ],
    'licence_renewal_days' => env('LICENCE_RENEWAL_DAYS', 30),
    'licence_free_activation_date' => '2026-07-10',

    'legacy_restaurant' => [
        'driver' => 'mysql',
        'host' => env('LEGACY_RESTAURANT_DB_HOST', '127.0.0.1'),
        'port' => env('LEGACY_RESTAURANT_DB_PORT', '3306'),
        'database' => env('LEGACY_RESTAURANT_DB_DATABASE', 'cdgym_info'),
        'username' => env('LEGACY_RESTAURANT_DB_USERNAME', 'root'),
        'password' => env('LEGACY_RESTAURANT_DB_PASSWORD', ''),
    ],

    'legacy_restaurant_remote' => [
        'driver' => 'mysql',
        'host' => env('LEGACY_RESTAURANT_REMOTE_DB_HOST', ''),
        'port' => env('LEGACY_RESTAURANT_REMOTE_DB_PORT', '3306'),
        'database' => env('LEGACY_RESTAURANT_REMOTE_DB_DATABASE', ''),
        'username' => env('LEGACY_RESTAURANT_REMOTE_DB_USERNAME', ''),
        'password' => env('LEGACY_RESTAURANT_REMOTE_DB_PASSWORD', ''),
    ],

    'materials_default_types' => [
        'Arbeitsblatt',
        'Merkblatt',
        'Präsentation',
        'Übung',
        'Test',
    ],
    'materials_type_icon_options' => [
        'mdi-file-document-outline',
        'mdi-note-text-outline',
        'mdi-text-box-outline',
        'mdi-file-question-outline',
        'mdi-check-decagram-outline',
        'mdi-clipboard-text-outline',
        'mdi-presentation',
        'mdi-monitor-dashboard',
        'mdi-link-variant',
        'mdi-web',
        'mdi-image-outline',
        'mdi-video-outline',
        'mdi-music-note-outline',
        'mdi-chart-box-outline',
        'mdi-flask-outline',
        'mdi-calculator-variant-outline',
        'mdi-atom-variant',
        'mdi-earth',
        'mdi-book-open-page-variant-outline',
        'mdi-lightbulb-outline',
        'mdi-book-outline',
        'mdi-book-open-variant',
        'mdi-library',
        'mdi-pencil-outline',
        'mdi-pen',
        'mdi-information',
        'mdi-ruler',
        'mdi-compass-outline',
        'mdi-map-marker-outline',
        'mdi-translate',
        'mdi-alphabetical',
        'mdi-numeric',
        'mdi-clock-outline',
        'mdi-calendar-month-outline',
        'mdi-school-outline',
        'mdi-test-tube',
        'mdi-forum-outline',
        'mdi-head-snowflake-outline',
        'mdi-help-circle-outline',
        'mdi-clipboard-check-outline',
        'mdi-format-list-bulleted',
        'mdi-format-list-numbered',
        'mdi-table',
        'mdi-code-tags',
        'mdi-console-line',
        'mdi-language-html5',
        'mdi-target',
        'mdi-exclamation',
        'mdi-gamepad-variant-outline',
        'mdi-trophy-outline',
    ],
    'eu_allergens' => [
        ['character' => 'A', 'short_description' => 'Glutenhaltiges Getreide'],
        ['character' => 'B', 'short_description' => 'Krebstiere'],
        ['character' => 'C', 'short_description' => 'Eier'],
        ['character' => 'D', 'short_description' => 'Fisch'],
        ['character' => 'E', 'short_description' => 'Erdnüsse'],
        ['character' => 'F', 'short_description' => 'Soja'],
        ['character' => 'G', 'short_description' => 'Milch oder Laktose'],
        ['character' => 'H', 'short_description' => 'Schalenfrüchte'],
        ['character' => 'L', 'short_description' => 'Sellerie'],
        ['character' => 'M', 'short_description' => 'Senf'],
        ['character' => 'N', 'short_description' => 'Sesam'],
        ['character' => 'O', 'short_description' => 'Sulfite'],
        ['character' => 'P', 'short_description' => 'Lupinen'],
        ['character' => 'R', 'short_description' => 'Weichtiere'],
    ],
    'teaching_max_schools_shown' => (int) env('TEACHING_MAX_SCHOOLS_SHOWN', 20),
    'import116_reset_max_runs' => (int) env('IMPORT116_RESET_MAX_RUNS', 5),
    'import116_runs_history_limit' => (int) env('IMPORT116_RUNS_HISTORY_LIMIT', 10),

    'licences' => [
        [
            'name' => 'Anmeldetool',
            'long_name' => 'Tool zum Verwalten von Anmeldungen',
            'price_per_year' => 200,
            'start_day_month' => '01.08.',
            'school_licence_enabled' => true,
            'admin_licence_enabled' => false,
            'admin_role_names' => null,
            'user_licence_enabled' => false,
            'user_role_names' => null,
        ],
        [
            'name' => 'Nachhilfetool',
            'long_name' => 'Tool zum Verwalten von Nachhilfe',
            'price_per_year' => 200,
            'start_day_month' => '01.08.',
            'school_licence_enabled' => true,
            'admin_licence_enabled' => false,
            'admin_role_names' => null,
            'user_licence_enabled' => false,
            'user_role_names' => null,
        ],
        [
            'name' => 'Lehrertool',
            'long_name' => 'Tool zum Verwalten von Unterricht',
            'price_per_year' => 200,
            'start_day_month' => '01.08.',
            'school_licence_enabled' => true,
            'admin_licence_enabled' => false,
            'admin_role_names' => null,
            'user_licence_enabled' => false,
            'user_role_names' => null,
        ],
        [
            'name' => 'Materialientool',
            'long_name' => 'Tool zum Verwalten von Unterrichtsmaterialien',
            'price_per_year' => 200,
            'start_day_month' => '01.08.',
            'school_licence_enabled' => true,
            'admin_licence_enabled' => false,
            'admin_role_names' => null,
            'user_licence_enabled' => false,
            'user_role_names' => null,
        ],
        [
            'name' => 'ABA',
            'long_name' => 'Tool zum Auswerten von Abschlussarbeiten',
            'price_per_year' => 200,
            'start_day_month' => '01.08.',
            'school_licence_enabled' => true,
            'admin_licence_enabled' => false,
            'admin_role_names' => null,
            'user_licence_enabled' => false,
            'user_role_names' => null,
        ],
        [
            'name' => 'Restaurant',
            'long_name' => 'Tool zum Verwalten des Restaurants',
            'price_per_year' => 200,
            'start_day_month' => '01.08.',
            'school_licence_enabled' => true,
            'admin_licence_enabled' => false,
            'admin_role_names' => null,
            'user_licence_enabled' => false,
            'user_role_names' => null,
        ],
    ],

    'schoolyears' => [
        ['name' => 'Schuljahr 2025/26', 'from' => '2025-09-08', 'sem_2_start' => '2026-02-16', 'to' => '2026-07-10', 'concerns' => '2025/26'],
        ['name' => 'Schuljahr 2026/27', 'from' => '2026-09-14', 'sem_2_start' => '2027-02-15', 'to' => '2027-07-09', 'concerns' => '2026/27'],
        ['name' => 'Schuljahr 2027/28', 'from' => '2027-09-13', 'sem_2_start' => '2028-02-21', 'to' => '2028-07-07', 'concerns' => '2027/28'],
        ['name' => 'Schuljahr 2028/29', 'from' => '2028-09-11', 'sem_2_start' => '2029-02-19', 'to' => '2029-07-06', 'concerns' => '2028/29'],
        ['name' => 'Schuljahr 2029/30', 'from' => '2029-09-10', 'sem_2_start' => '2030-02-18', 'to' => '2030-07-05', 'concerns' => '2029/30'],
        ['name' => 'Schuljahr 2030/31', 'from' => '2030-09-09', 'sem_2_start' => '2031-02-17', 'to' => '2031-07-04', 'concerns' => '2030/31'],
        ['name' => 'Schuljahr 2031/32', 'from' => '2031-09-08', 'sem_2_start' => '2032-02-16', 'to' => '2032-07-09', 'concerns' => '2031/32'],
        ['name' => 'Schuljahr 2032/33', 'from' => '2032-09-13', 'sem_2_start' => '2033-02-21', 'to' => '2033-07-08', 'concerns' => '2032/33'],
        ['name' => 'Schuljahr 2033/34', 'from' => '2033-09-12', 'sem_2_start' => '2034-02-20', 'to' => '2034-07-07', 'concerns' => '2033/34'],
        ['name' => 'Schuljahr 2034/35', 'from' => '2034-09-11', 'sem_2_start' => '2035-02-19', 'to' => '2035-07-06', 'concerns' => '2034/35'],
        ['name' => 'Schuljahr 2035/36', 'from' => '2035-09-10', 'sem_2_start' => '2036-02-18', 'to' => '2036-07-04', 'concerns' => '2035/36'],
    ],
];
