import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('AbaDetails', () => {
    it('renders the basic information card and wires the extraction flow', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain('ABA Details')
        expect(source).toContain('Extraktion starten')
        expect(source).toContain('Dokumentinhalte aus dem Hauptdokument extrahieren')
        expect(source).toContain('{{ savedAbaTitle }}')
        expect(source).toContain('Verfasser:in: {{ savedAbaStudentName }}')
        expect(source).toContain('savedAbaTitle() {')
        expect(source).toContain('savedAbaStudentName() {')
        expect(source).toContain('Hauptdokument')
        expect(source).toContain('Weitere Dokumente')
        expect(source).toContain('section.key === \'title_page\' && section.title_page')
        expect(source).toContain('title-page-details__hero-label">Titel')
        expect(source).toContain('Verfasser:in')
        expect(source).toContain('Betreuer:in')
        expect(source).toContain('Gefundene Bilder')
        expect(source).toContain('Seitenzahl')
        expect(source).toContain('Schule (vollständig)')
        expect(source).toContain('Name')
        expect(source).toContain('Straße')
        expect(source).toContain('Ort')
        expect(source).toContain('titlePageSchoolDetailItem(section)')
        expect(source).toContain('buildEditableTitlePageItem(section, \'author\')')
        expect(source).toContain('resolveTitlePageSchoolParts(section)')
        expect(source).toContain('title-page-details__item-lines')
        expect(source).toContain('v-if="item.value !== null"')
        expect(source).toContain("value: lines.length ? null : (school.full || '–')")
        expect(source).not.toContain('Weitere Angaben vom Titelblatt')
        expect(source).not.toContain('Hinweise zur Erkennung')
        expect(source).toContain("section.key === 'table_of_contents' && tableOfContentsEntries(section).length")
        expect(source).toContain('class="toc-details"')
        expect(source).toContain('class="toc-details__entry"')
        expect(source).toContain("section.preview_text && !['title_page', 'table_of_contents'].includes(section.key)")
        expect(source).toContain('extraction-section-card__chips')
        expect(source).not.toContain('Extrahierter Dokumentkopf')
        expect(source).toContain('await axios.get(`/api/admin/abas/${this.abaId}`)')
        expect(source).toContain("await axios.get(`/api/admin/abas/${this.abaId}/extraction`)")
        expect(source).toContain('Felder überschreiben')
        expect(source).toContain('overwriteExistingExtractionFields: false')
        expect(source).toContain("overwrite_existing_fields: this.overwriteExistingExtractionFields")
        expect(source).toContain("await axios.post(`/api/admin/abas/${this.abaId}/extraction`, {")
        expect(source).toContain('pendingOverwriteExtractionRunId')
        expect(source).toContain('refreshAbaAfterOverwriteExtractionIfNeeded()')
        expect(source).toContain('extraction-header-actions')
        expect(source).toContain('Status:')
        expect(source).toContain(':color="extractionStatusColor"')
        expect(source).toContain(':prepend-icon="extractionStatusIcon"')
        expect(source).toContain('this.scheduleExtractionPoll()')
        expect(source).toContain('currentExtraction.status === \'completed\'')
        expect(source).toContain('Nicht zugeordnete Blöcke')
        expect(source).toContain("$router.push('/admin/aba')")
        expect(source).not.toContain('Letzte Extraktion')
        expect(source).not.toContain('DOCX-Hauptdokumente werden gegen das ABA-Regelwerk geprüft und in strukturierte Bereiche zerlegt.')
    })

    it('offers pencil-based editing for title page fields and saves through the aba endpoint', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain('icon="mdi-pencil"')
        expect(source).toContain('openTitlePageEditDialog(\'title\', titlePageHeroTitle(section))')
        expect(source).toContain('openTitlePageEditDialog(\'subtitle\', titlePageHeroSubtitle(section))')
        expect(source).toContain('openTitlePageEditDialog(item.editKey, item.editValue)')
        expect(source).toContain('titlePageEditDialog.open')
        expect(source).toContain('titlePageFieldConfig(fieldKey)')
        expect(source).toContain('titlePageEditPayload(fieldKey, value)')
        expect(source).toContain('saveTitlePageEdit()')
        expect(source).toContain("await axios.put(`/api/admin/abas/${this.abaId}`, {")
        expect(source).toContain('subtitle: [this.titlePageOverrides.subtitle, titlePage.subtitle]')
        expect(source).toContain('title_page_overrides: { subtitle: value || null }')
        expect(source).toContain('title_page_overrides: { advisor: value || null }')
        expect(source).toContain('title_page_overrides: { school_full: value || null }')
        expect(source).toContain('title_page_overrides: { date: value || null }')
    })

    it('renders structured table of contents entries in the extraction card', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain('tableOfContentsEntries(section)')
        expect(source).toContain('visibleSectionWarnings(section)')
        expect(source).toContain('Mehrere ähnliche Abschnittskandidaten erkannt.')
        expect(source).toContain('Inhaltsverzeichnisse erkannt; angezeigt wird die passendste Variante.')
        expect(source).toContain('const entries = section?.table_of_contents?.entries')
        expect(source).toContain("entries.filter((entry) => String(entry || '').trim() !== '')")
        expect(source).toContain('.toc-details__entry')
        expect(source).not.toContain('sectionHeaderHints(section)')
    })

    it('binds the basis and extraction navigation to the url query', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain('@click="selectTab(item.key)"')
        expect(source).toContain("'$route.query':")
        expect(source).toContain('this.applyRouteTabSelection()')
        expect(source).toContain("const routeValue = String(this.$route?.query?.tab || '').trim().toLowerCase()")
        expect(source).toContain("const allowed = ['basis', 'extraction']")
        expect(source).toContain('const navigation = this.$router.replace({')
        expect(source).toContain('tab: normalized')
    })

    it('adapts title page image backgrounds based on the loaded image colors', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain(':style="titlePageImageSurfaceStyle(image)"')
        expect(source).toContain('@load="handleTitlePageImageLoad(image, $event)"')
        expect(source).toContain('titlePageImageStyles: {}')
        expect(source).toContain('document.createElement(\'canvas\')')
        expect(source).toContain('buildTitlePageImagePresentation({')
        expect(source).toContain('rgbToHsl(red, green, blue)')
        expect(source).toContain('--title-page-image-surface-background')
        expect(source).toContain('justify-content: center;')
        expect(source).toContain('width: auto;')
        expect(source).toContain('max-width: 100%;')
        expect(source).toContain('max-height: 100%;')
        expect(source).not.toContain('title-page-details__image-caption')
        expect(source).not.toContain('title-page-details__image-tags')
        expect(source).not.toContain('image.position || image.type')
    })

    it('shows a next aba navigation button when the detail payload provides one', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain('Nächste ABA')
        expect(source).toContain('@click="goToNextAba"')
        expect(source).toContain('nextAba() {')
        expect(source).toContain('path: `/admin/aba/details/${this.nextAba.id}`')
    })

    it('reloads the aba details when only the route aba id changes', () => {
        const source = readFileSync('resources/js/pages/admin/aba/AbaDetails.vue', 'utf8')

        expect(source).toContain('abaId(value, previousValue) {')
        expect(source).toContain('this.handleAbaNavigationChange()')
        expect(source).toContain('handleAbaNavigationChange() {')
        expect(source).toContain('this.extractionResult = null')
        expect(source).toContain('this.titlePageImageStyles = {}')
        expect(source).toContain('this.loadAba()')
    })
})
