import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('homepage restaurant auth flow', () => {
    it('checks the email before showing the next restaurant login step', () => {
        const componentPath = resolve(process.cwd(), 'resources/js/pages/homepage/index/Restaurant.vue')
        const source = readFileSync(componentPath, 'utf8')

        expect(source).toContain("axios.post('/api/homepage/restaurant/check_email'")
        expect(source).toContain('class="restaurant-login-school"')
        expect(source).toContain('{{ schoolInfoName }}')
        expect(source).toContain('<v-form v-if="!loginCheckResult" ref="loginEmailForm" @submit.prevent="submitLoginEmailCheck">')
        expect(source).toContain('autofocus')
        expect(source).toContain(':rules="[required(), mail(), maxLength(255)]"')
        expect(source).toContain('class="restaurant-login-email mb-3"')
        expect(source).toContain('v-if="loginCheckResult?.email"')
        expect(source).toContain('{{ loginCheckResult.email }}')
        expect(source).toContain("loginCheckResult?.status === 'USER_FOUND'")
        expect(source).toContain("loginCheckResult?.status === 'PENDING_CONFIRMATION'")
        expect(source).toContain('{{ loginCheckResult.message }}')
        expect(source).toContain("v-if=\"loginCheckResult?.status !== 'PENDING_CONFIRMATION'\"")
        expect(source).toContain('Mit Code')
        expect(source).toContain('Mit Passwort')
        expect(source).toContain(":variant=\"loginMode === 'code' ? 'flat' : 'outlined'\"")
        expect(source).toContain(":variant=\"loginMode === 'password' ? 'flat' : 'outlined'\"")
        expect(source).toContain("axios.post('/api/homepage/restaurant/send_login_code'")
        expect(source).toContain("axios.post('/api/homepage/restaurant/login_with_code'")
        expect(source).toContain("axios.post('/api/homepage/restaurant/login_with_password'")
        expect(source).toContain('loginSelectedUserId')
        expect(source).toContain('selectedLoginUser')
        expect(source).toContain('loginCodeToken')
        expect(source).toContain('loginPassword')
        expect(source).toContain('startCodeLogin')
        expect(source).toContain('startPasswordLogin')
        expect(source).toContain('sendRestaurantLoginCode')
        expect(source).toContain('submitRestaurantCodeLogin')
        expect(source).toContain('submitRestaurantPasswordLogin')
        expect(source).toContain('window.location.href = `/homepage/restaurant?school=${this.currentSchoolShortName}`')
        expect(source).toContain('loginPrimaryActionLabel')
        expect(source).toContain("return 'Schließen'")
    })

    it('offers registration when the restaurant email is unknown', () => {
        const componentPath = resolve(process.cwd(), 'resources/js/pages/homepage/index/Restaurant.vue')
        const source = readFileSync(componentPath, 'utf8')

        expect(source).toContain('Anmelden/Registrieren')
        expect(source).not.toContain('@click="openRegisterDialog">Registrieren</v-btn>')
        expect(source).toContain("loginCheckResult?.status === 'REGISTER_REQUIRED'")
        expect(source).toContain('Möchten Sie sich registrieren?')
        expect(source).toContain("loginCheckLoading || loginCheckResult?.status === 'REGISTER_REQUIRED'")
        expect(source).toContain('@click="handleLoginPrimaryAction"')
        expect(source).toContain('{{ loginPrimaryActionLabel }}')
        expect(source).toContain("return 'Registrieren'")
        expect(source).toContain('switchToRegisterDialog')
        expect(source).toContain('await this.switchToRegisterDialog()')
        expect(source).toContain("if (this.registerSource === 'new_user')")
        expect(source).toContain('await this.$nextTick()')
        expect(source).toContain("axios.post('/api/homepage/restaurant/register'")
        expect(source).toContain("axios.post('/api/homepage/restaurant/confirm_email'")
        expect(source).toContain('<div v-if="registerEmail" class="restaurant-login-email mb-3">')
        expect(source).toContain('<div class="restaurant-login-email__value">{{ registerEmail }}</div>')
        expect(source).toContain("registerSource === 'new_user'")
        expect(source).toContain("registerResult?.status === 'ENTER_USER_DATA'")
        expect(source).toContain("registerResult?.status !== 'REGISTERED'")
        expect(source).toContain('registerEmailToken')
        expect(source).toContain('registerConfirmationToken')
        expect(source).toContain('registerPasswordChoicePrompted')
        expect(source).toContain("Möchten Sie jetzt ein Passwort für spätere Anmeldungen festlegen?")
        expect(source).toContain("setRegisterPasswordIntent('yes')")
        expect(source).toContain("setRegisterPasswordIntent('no')")
        expect(source).toContain('registerShouldAskForPasswordInput')
        expect(source).toContain('label="Passwort"')
        expect(source).toContain(':rules="[required(), minLength(8), maxLength(255)]"')
        expect(source).toContain('password: this.registerShouldAskForPasswordInput ? this.registerPassword : null')
        expect(source).toContain('retryRestaurantRegistrationEmail')
        expect(source).toContain('handleRegisterPrimaryAction')
        expect(source).toContain('registerPrimaryActionLabel')
        expect(source).toContain('submitRestaurantRegistration')
        expect(source).toContain('openRegisterDialog() {')
        expect(source).toContain('this.openLoginDialog()')
        expect(source).toContain("return this.config?.restaurant?.new_users_must_confirm_email === true")
        expect(source).toContain('wird ein neuer lunch_user angelegt und direkt angemeldet')
    })

    it('shows the logged-in restaurant user and logout action', () => {
        const componentPath = resolve(process.cwd(), 'resources/js/pages/homepage/index/Restaurant.vue')
        const source = readFileSync(componentPath, 'utf8')

        expect(source).toContain('v-if="restaurantAuthUser" class="restaurant-auth-card"')
        expect(source).toContain('{{ restaurantAuthDisplayName }}')
        expect(source).toContain('{{ restaurantAuthEmail }}')
        expect(source).toContain('E-Mail: {{ restaurantAuthEmail }}')
        expect(source).toContain('Sie sind angemeldet und können jetzt Menüs bestellen.')
        expect(source).toContain('openRestaurantPasswordDialog')
        expect(source).toContain("axios.post('/api/homepage/restaurant/change_password'")
        expect(source).toContain('Passwort ändern')
        expect(source).toContain('Passwort speichern')
        expect(source).toContain('>Abmelden</v-btn>')
        expect(source).toContain('logoutRestaurantUser')
        expect(source).toContain("return this.config?.auth_check === true ? this.config?.auth_user || null : null")
        expect(source).toContain("return this.restaurantAuthUser?.email?.trim?.() || ''")
        expect(source).toContain('await this.homepageStore.logout()')
    })
})
