import { cleanup, fireEvent, render, screen, within } from '@testing-library/vue'
import { afterEach, describe, expect, it } from 'vitest'
import MaturaSetup from '@/pages/admin/helpers/matura/MaturaSetup.vue'

const roster = [
    { id: 1, first_name: 'Änne', last_name: 'Müller', class: '8A' },
    { id: 2, first_name: 'Emil', last_name: 'Öztürk', class: '8A' },
    { id: 3, first_name: 'Zoë', last_name: 'Groß', class: '8B' },
]

function task(title) { return screen.getByRole('button', { name: new RegExp(`^[1-3✓] ${title} `) }) }
async function done() { await fireEvent.click(screen.getByRole('button', { name: 'Übernehmen' })) }
function classButton(name) { return screen.getByRole('button', { name: new RegExp(`^${name} `) }) }
async function basics() {
    await fireEvent.click(task('Matura & Klassen'))
    await fireEvent.update(screen.getByLabelText('Name der Matura'), 'Deutsch')
    await fireEvent.update(screen.getByLabelText('Prüfungsdatum'), '2026-10-04')
    await fireEvent.click(classButton('8A'))
    await fireEvent.click(classButton('8B'))
    await done()
}
async function firstRoom() {
    await fireEvent.click(task('Räume & Schüler'))
    await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum A')
    await done()
}
function mountSetup(props = {}) { return render(MaturaSetup, { props: { schoolyearId: 10, roster, ...props } }) }
afterEach(cleanup)

describe('00-Manager setup tasks', () => {
    it('unlocks validated tasks in order and saves only from the final summary', async () => {
        const view = mountSetup()
        expect(task('Räume & Schüler')).toBeDisabled()
        expect(task('Ablauf')).toBeDisabled()
        expect(screen.queryByLabelText('Name der Matura')).not.toBeInTheDocument()
        await fireEvent.click(task('Matura & Klassen'))
        await done()
        expect(screen.getByRole('alert')).toHaveTextContent('Bitte gib der Matura einen Namen.')
        expect(task('Räume & Schüler')).toBeDisabled()
        await fireEvent.update(screen.getByLabelText('Name der Matura'), 'Deutsch')
        await fireEvent.update(screen.getByLabelText('Prüfungsdatum'), '')
        await done()
        expect(task('Räume & Schüler')).toBeDisabled()
        await fireEvent.update(screen.getByLabelText('Prüfungsdatum'), '2026-10-04')
        await fireEvent.keyDown(screen.getByLabelText('Name der Matura'), { key: 'Enter' })
        await fireEvent.submit(screen.getByLabelText('Name der Matura').closest('form'))
        expect(view.emitted().save).toBeUndefined()
        expect(task('Räume & Schüler')).toBeDisabled()
        await done()
        expect(task('Räume & Schüler')).toBeEnabled()
        await firstRoom()
        await fireEvent.click(task('Ablauf'))
        expect(screen.queryByLabelText('Name der Matura')).not.toBeInTheDocument()
        expect(screen.queryByPlaceholderText('z. B. 3.12')).not.toBeInTheDocument()
        await fireEvent.update(screen.getByRole('spinbutton'), '11')
        await done()
        expect(screen.getByRole('alert')).toHaveTextContent('0 bis 10')
        await fireEvent.update(screen.getByRole('spinbutton'), '0')
        await done()
        expect(screen.getByRole('heading', { name: 'Alles bereit?' })).toBeInTheDocument()
        expect(screen.getByText(/0 Warteplätze/)).toBeInTheDocument()
        expect(view.emitted().save).toBeUndefined()
        await fireEvent.click(screen.getByRole('button', { name: 'Matura speichern' }))
        expect(view.emitted().save[0][0]).toEqual({ schoolyear_id: 10, name: 'Deutsch', exam_date: '2026-10-04', waiting_places: 0, rooms: [{ name: 'Raum A', student_ids: [], manual_students: [] }] })
    })

    it('focuses one room, preserves filters and students, and prevents duplicate assignments', async () => {
        const view = mountSetup()
        await basics()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum A')
        await fireEvent.update(screen.getByLabelText('Klasse filtern'), '8A')
        await fireEvent.update(screen.getByPlaceholderText('Nachname oder Vorname'), 'Müller')
        await fireEvent.click(screen.getByRole('checkbox', { name: /Müller Änne/ }))
        await fireEvent.click(screen.getByText('Weitere Schüler ohne Import hinzufügen'))
        await fireEvent.update(screen.getByPlaceholderText('Nachname Vorname'), '  Gast Eins\n\nGast Zwei ')
        await fireEvent.click(screen.getByRole('button', { name: '+ Raum hinzufügen' }))
        expect(screen.getAllByPlaceholderText('z. B. 3.12')).toHaveLength(1)
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum B')
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).toBeDisabled()
        await fireEvent.click(screen.getByRole('checkbox', { name: /Öztürk Emil/ }))
        await fireEvent.click(screen.getByRole('checkbox', { name: /Groß Zoë/ }))
        await fireEvent.click(screen.getByRole('button', { name: 'Vorheriger Raum' }))
        expect(screen.getByLabelText('Klasse filtern')).toHaveValue('8A')
        expect(screen.getByPlaceholderText('Nachname oder Vorname')).toHaveValue('Müller')
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).toBeChecked()
        expect(screen.getByPlaceholderText('Nachname Vorname')).toHaveValue('  Gast Eins\n\nGast Zwei ')
        await done()
        await fireEvent.click(task('Ablauf'))
        await done()
        await fireEvent.click(screen.getByRole('button', { name: 'Matura speichern' }))
        expect(view.emitted().save[0][0].rooms).toEqual([
            { name: 'Raum A', student_ids: [1], manual_students: [{ name: 'Gast Eins' }, { name: 'Gast Zwei' }] },
            { name: 'Raum B', student_ids: [2, 3], manual_students: [] },
        ])
    })

    it('validates every room, reveals an invalid room and allows its removal', async () => {
        mountSetup()
        await basics()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum A')
        await fireEvent.click(screen.getByRole('button', { name: '+ Raum hinzufügen' }))
        await fireEvent.click(screen.getByRole('button', { name: 'Vorheriger Raum' }))
        await done()
        expect(screen.getByRole('alert')).toHaveTextContent('jedem Raum einen Namen')
        expect(screen.getByPlaceholderText('z. B. 3.12')).toHaveValue('')
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum A')
        await done()
        expect(screen.getByRole('alert')).toHaveTextContent('eigenen Namen')
        await fireEvent.click(screen.getByRole('button', { name: 'Raum entfernen' }))
        expect(screen.queryByRole('button', { name: 'Raum entfernen' })).not.toBeInTheDocument()
        await done()
        expect(task('Ablauf')).toBeEnabled()
    })

    it('retains values while invalidating dependent completions after editing a completed task', async () => {
        mountSetup()
        await basics()
        await firstRoom()
        await fireEvent.click(task('Ablauf'))
        await fireEvent.update(screen.getByRole('spinbutton'), '4')
        await done()
        await fireEvent.click(task('Räume & Schüler'))
        expect(task('Räume & Schüler')).toHaveTextContent('✓')
        await fireEvent.update(screen.getByPlaceholderText('Nachname oder Vorname'), 'Müller')
        expect(task('Räume & Schüler')).toHaveTextContent('✓')
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum C')
        expect(task('Räume & Schüler')).not.toHaveTextContent('✓')
        expect(task('Ablauf')).toBeDisabled()
        await done()
        await fireEvent.click(task('Matura & Klassen'))
        expect(screen.getByLabelText('Name der Matura')).toHaveValue('Deutsch')
        await fireEvent.update(screen.getByLabelText('Name der Matura'), 'Mathematik')
        expect(task('Räume & Schüler')).toBeDisabled()
        await done()
        await fireEvent.click(task('Räume & Schüler'))
        expect(screen.getByPlaceholderText('z. B. 3.12')).toHaveValue('Raum C')
        await done()
        await fireEvent.click(task('Ablauf'))
        expect(screen.getByRole('spinbutton')).toHaveValue(4)
        await done()
        expect(screen.getByText('Mathematik')).toBeInTheDocument()
    })

    it('restores an existing setup and retains the 40-room limit', async () => {
        const rooms = Array.from({ length: 40 }, (_, index) => ({ id: index + 1, name: `Raum ${index + 1}` }))
        mountSetup({ existing: { session: { name: 'Bestehende Matura', exam_date: '2026-10-04T00:00:00Z', waiting_places: 3 }, rooms, students: [{ matura_room_id: 1, import116_id: 1, name: 'Müller Änne' }, { matura_room_id: 1, import116_id: null, name: 'Gast Eins' }] } })
        await fireEvent.click(task('Matura & Klassen'))
        expect(screen.getByLabelText('Name der Matura')).toHaveValue('Bestehende Matura')
        expect(screen.getByLabelText('Prüfungsdatum')).toHaveValue('2026-10-04')
        expect(classButton('8A')).toHaveAttribute('aria-pressed', 'true')
        await done()
        await fireEvent.click(task('Räume & Schüler'))
        expect(screen.getByRole('button', { name: '+ Raum hinzufügen' })).toBeDisabled()
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).toBeChecked()
        expect(screen.getByPlaceholderText('Nachname Vorname')).toHaveValue('Gast Eins')
        await done()
        await fireEvent.click(task('Ablauf'))
        expect(screen.getByRole('spinbutton')).toHaveValue(3)
    })

    it('rejects too many manual students and overlong names before completing the room task', async () => {
        mountSetup()
        await basics()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'A')
        await fireEvent.click(screen.getByText('Weitere Schüler ohne Import hinzufügen'))
        await fireEvent.update(screen.getByPlaceholderText('Nachname Vorname'), Array(201).fill('Gast').join('\n'))
        await done()
        expect(screen.getByRole('alert')).toHaveTextContent('200 weitere Schüler')
        await fireEvent.update(screen.getByPlaceholderText('Nachname Vorname'), 'A'.repeat(181))
        await done()
        expect(screen.getByRole('alert')).toHaveTextContent('180 Zeichen')
        expect(task('Ablauf')).toBeDisabled()
    })

    it('restores selections against the current roster and requires confirming stale assignments again', async () => {
        const view = mountSetup({ draft: {
            form: { name: 'Entwurf', exam_date: '2026-10-04', waiting_places: 2, rooms: [
                { name: 'A', student_ids: [1, 99], manualText: 'Gast', classFilter: '8A', search: '' },
                { name: 'B', student_ids: [1, 2], manualText: '', classFilter: '', search: '' },
            ] }, completed: [true, true, true], activeStep: null, roomIndex: 1,
        } })
        expect(screen.getByText(/Einige Schüler sind nicht mehr/)).toBeInTheDocument()
        expect(screen.getByPlaceholderText('z. B. 3.12')).toHaveValue('B')
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).toBeDisabled()
        expect(screen.getByRole('checkbox', { name: /Öztürk Emil/ })).toBeChecked()
        expect(task('Ablauf')).toBeDisabled()
        const draft = view.emitted().draft.at(-1)[0]
        expect(draft.form.rooms[0].student_ids).toEqual([1])
        expect(draft.form.rooms[1].student_ids).toEqual([2])
        expect(draft.form.rooms[0].manualText).toBe('Gast')
        expect(draft.completed).toEqual([true, false, false])
        expect(view.emitted().save).toBeUndefined()
    })

    it('limits the pool to globally selected classes without automatically assigning students', async () => {
        const view = mountSetup()
        await basics()
        expect(view.emitted().draft.at(-1)[0].form.rooms[0].student_ids).toEqual([])
        await fireEvent.click(task('Matura & Klassen'))
        await fireEvent.click(classButton('8B'))
        await done()
        await fireEvent.click(task('Räume & Schüler'))
        expect(screen.queryByRole('button', { name: /^8A / })).not.toBeInTheDocument()
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'A')
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).not.toBeChecked()
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ }).closest('.zero-roster')).toHaveClass('zero-roster--single-class')
        expect(screen.queryByRole('checkbox', { name: /Groß Zoë/ })).not.toBeInTheDocument()
        expect(screen.queryByRole('option', { name: '8B' })).not.toBeInTheDocument()
        await fireEvent.click(screen.getByText('Weitere Schüler ohne Import hinzufügen'))
        await fireEvent.update(screen.getByPlaceholderText('Nachname Vorname'), 'Gast')
        await fireEvent.click(screen.getByRole('checkbox', { name: /Müller Änne/ }))
        await done()
        await fireEvent.click(task('Matura & Klassen'))
        await fireEvent.click(classButton('8A'))
        expect(screen.getByText(/1 Schülerzuordnungen wurden entfernt/)).toBeInTheDocument()
        expect(task('Räume & Schüler')).toBeDisabled()
        expect(task('Ablauf')).toBeDisabled()
        await done()
        await fireEvent.click(task('Räume & Schüler'))
        expect(screen.getByPlaceholderText('Nachname Vorname')).toHaveValue('Gast')
        expect(screen.queryByRole('checkbox', { name: /Müller Änne/ })).not.toBeInTheDocument()
        await done()
        await fireEvent.click(task('Ablauf'))
        await done()
        await fireEvent.click(screen.getByRole('button', { name: 'Matura speichern' }))
        expect(view.emitted().save[0][0].rooms).toEqual([{ name: 'A', student_ids: [], manual_students: [{ name: 'Gast' }] }])
    })

    it('protects individual assignments across rooms and releases students after deselection', async () => {
        const view = mountSetup()
        await basics()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'A')
        await fireEvent.click(screen.getByRole('checkbox', { name: /Müller Änne/ }))
        await fireEvent.click(screen.getByRole('button', { name: '+ Raum hinzufügen' }))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'B')
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).toBeDisabled()
        await fireEvent.click(screen.getByRole('checkbox', { name: /Groß Zoë/ }))
        await fireEvent.click(screen.getByRole('button', { name: 'Vorheriger Raum' }))
        await fireEvent.click(screen.getByRole('checkbox', { name: /Müller Änne/ }))
        await fireEvent.click(screen.getByRole('button', { name: 'Nächster Raum' }))
        expect(screen.getByRole('checkbox', { name: /Müller Änne/ })).toBeEnabled()
        await fireEvent.click(screen.getByRole('checkbox', { name: /Müller Änne/ }))
        expect(view.emitted().draft.at(-1)[0].form.rooms.map((item) => item.student_ids)).toEqual([[], [3, 1]])
    })

    it('derives class choices from legacy draft IDs without adding excluded students', async () => {
        const view = mountSetup({ draft: {
            form: { name: 'Entwurf', exam_date: '2026-10-04', waiting_places: 2, rooms: [
                { name: 'A', student_ids: [1, 3], manualText: 'Gast', classFilter: '', search: '' },
            ] }, completed: [true, true, false], activeStep: 1, roomIndex: 0,
        } })
        expect(view.emitted().draft.at(-1)[0].form.rooms[0].student_ids).toEqual([1, 3])
        expect(screen.getByRole('checkbox', { name: /Öztürk Emil/ })).not.toBeChecked()
        await fireEvent.click(task('Matura & Klassen'))
        expect(classButton('8A')).toHaveAttribute('aria-pressed', 'true')
        expect(classButton('8B')).toHaveAttribute('aria-pressed', 'true')
    })

    it('groups an unsorted roster naturally by class and alphabetically by surname and first name', async () => {
        const unsortedRoster = [
            { id: 4, first_name: 'Emil', last_name: 'Zulu', class: '10A' },
            { id: 3, first_name: 'Emil', last_name: 'Öztürk', class: '2A' },
            { id: 1, first_name: 'Zoë', last_name: 'Müller', class: '2A' },
            { id: 2, first_name: 'Änne', last_name: 'Müller', class: '2A' },
            { id: 5, first_name: 'Karl', last_name: 'Alpha', class: '10A' },
            { id: 6, first_name: 'Ohne', last_name: 'Klasse', class: '' },
        ]
        const view = mountSetup({ roster: unsortedRoster })
        await fireEvent.click(task('Matura & Klassen'))
        await fireEvent.update(screen.getByLabelText('Name der Matura'), 'Deutsch')
        const classNames = screen.getAllByRole('button', { name: /Schüler verfügbar/ }).map((button) => button.textContent)
        expect(classNames).toEqual(['2A3 Schüler verfügbar', '10A2 Schüler verfügbar'])
        await fireEvent.click(classButton('10A'))
        await fireEvent.click(classButton('2A'))
        expect(view.emitted().draft.at(-1)[0].form.rooms[0].student_ids).toEqual([])
        await done()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'A')
        const ids = () => screen.getAllByRole('checkbox').map((checkbox) => checkbox.getAttribute('value'))
        expect(ids()).toEqual(['2', '1', '3', '5', '4'])
        const list = screen.getAllByRole('checkbox')[0].closest('.zero-roster')
        expect(list).not.toHaveClass('zero-roster--single-class')
        expect(screen.getAllByRole('heading', { level: 4 }).map((heading) => heading.textContent)).toEqual(['2A', '10A'])
        expect(screen.getAllByRole('option').map((option) => option.textContent)).toEqual(['Alle teilnehmenden Klassen', '2A', '10A'])
        await fireEvent.update(screen.getByPlaceholderText('Nachname oder Vorname'), 'Müller')
        expect(ids()).toEqual(['2', '1'])
        expect(list).toHaveClass('zero-roster--single-class')
        expect(screen.queryByRole('heading', { name: '10A' })).not.toBeInTheDocument()
        await fireEvent.update(screen.getByPlaceholderText('Nachname oder Vorname'), '')
        expect(list).not.toHaveClass('zero-roster--single-class')
        await fireEvent.update(screen.getByLabelText('Klasse filtern'), '10A')
        expect(ids()).toEqual(['5', '4'])
        expect(list).toHaveClass('zero-roster--single-class')
        expect(screen.queryByRole('heading', { name: '2A' })).not.toBeInTheDocument()
    })

    it('shows confirmed results immediately and hides invalidated results until they are confirmed again', async () => {
        mountSetup()
        await basics()
        const basicsSummary = within(screen.getByRole('region', { name: 'Bestätigte Matura und Klassen' }))
        expect(basicsSummary.getByText('Deutsch')).toBeInTheDocument()
        expect(basicsSummary.getByText('04.10.2026')).toBeInTheDocument()
        expect(basicsSummary.getByText('8A, 8B')).toBeInTheDocument()
        expect(screen.queryByRole('region', { name: 'Bestätigte Räume und Schüler' })).not.toBeInTheDocument()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum A')
        await fireEvent.click(screen.getByRole('checkbox', { name: /Öztürk Emil/ }))
        await fireEvent.click(screen.getByRole('checkbox', { name: /Müller Änne/ }))
        await fireEvent.click(screen.getByText('Weitere Schüler ohne Import hinzufügen'))
        await fireEvent.update(screen.getByPlaceholderText('Nachname Vorname'), 'Gast Eins')
        await fireEvent.update(screen.getByPlaceholderText('Nachname oder Vorname'), 'Müller')
        await done()
        const roomSummary = within(screen.getByRole('region', { name: 'Bestätigte Räume und Schüler' }))
        expect(roomSummary.getByRole('heading', { name: 'Raum A' })).toBeInTheDocument()
        expect(roomSummary.getByText('3 Schüler')).toBeInTheDocument()
        await fireEvent.click(roomSummary.getByText('Schüler anzeigen'))
        expect(roomSummary.getAllByRole('listitem').map((item) => item.textContent)).toEqual(['Müller Änne', 'Öztürk Emil', 'Gast Eins'])
        expect(roomSummary.getByRole('heading', { name: '8A' })).toBeInTheDocument()
        expect(roomSummary.getByRole('heading', { name: 'Manuell hinzugefügt' })).toBeInTheDocument()
        await fireEvent.click(task('Ablauf'))
        await fireEvent.update(screen.getByRole('spinbutton'), '4')
        await done()
        expect(screen.getByRole('region', { name: 'Bestätigter Ablauf' })).toHaveTextContent('4 Warteplätze + 1 Toilettenplatz')
        expect(screen.getByRole('button', { name: 'Matura speichern' })).toBeInTheDocument()
        await fireEvent.click(task('Räume & Schüler'))
        await fireEvent.update(screen.getByPlaceholderText('z. B. 3.12'), 'Raum B')
        await fireEvent.click(screen.getByRole('button', { name: 'Zur Aufgabenübersicht' }))
        expect(screen.getByRole('region', { name: 'Bestätigte Matura und Klassen' })).toBeInTheDocument()
        expect(screen.queryByRole('region', { name: 'Bestätigte Räume und Schüler' })).not.toBeInTheDocument()
        expect(screen.queryByRole('region', { name: 'Bestätigter Ablauf' })).not.toBeInTheDocument()
        expect(screen.queryByText('Raum A')).not.toBeInTheDocument()
        expect(screen.queryByRole('button', { name: 'Matura speichern' })).not.toBeInTheDocument()
        await fireEvent.click(task('Räume & Schüler'))
        await done()
        expect(screen.getByRole('region', { name: 'Bestätigte Räume und Schüler' })).toHaveTextContent('Raum B')
        await fireEvent.click(task('Matura & Klassen'))
        await fireEvent.update(screen.getByLabelText('Name der Matura'), 'Mathematik')
        await fireEvent.click(screen.getByRole('button', { name: 'Zur Aufgabenübersicht' }))
        expect(screen.queryByRole('heading', { name: 'Übernommene Angaben' })).not.toBeInTheDocument()
        expect(screen.queryByText('Deutsch')).not.toBeInTheDocument()
        await fireEvent.click(task('Matura & Klassen'))
        await done()
        expect(screen.getByRole('region', { name: 'Bestätigte Matura und Klassen' })).toHaveTextContent('Mathematik')
        expect(screen.queryByRole('region', { name: 'Bestätigte Räume und Schüler' })).not.toBeInTheDocument()
    })
})
